INSERT INTO Event(eventId, userId, eventName, eventCategory, eventDesc, eventDate, startTime, endTime, address, totalTicket, ticketPrice, profileImage, bannerImage, rating, approvalStatus) 
VALUES (0, 0, 'TAYLOR SWIFT CONCERT', 'Concert', 'Join us for an unforgettable night with Taylor Swift...', '2024-03-15', '20:00', '23:00', 'Madison Square Garden, New York, NY', 1000, 100, '/sample_posters/small/s-0.avif', '/sample_posters/banner/concert.webp', 4.5, 'Approved'),
(1, 0, 'THE PHANTOM OF THE OPERA', 'Drama', 'Experience the magic of The Phantom of the Opera...', '2024-04-10', '19:00', '22:00', 'The Royal Opera House, London, UK', 1200, 150, '/sample_posters/small/s-1.jpg', '/sample_posters/banner/opera.jpg', 5.0, 'Approved'),
(2, 0, 'The New Yorker', 'Drama', 'Explore the bustling city of New York through the eyes of The New Yorker...', '2024-05-05', '18:30', '21:30', 'Times Square, New York, NY', 800, 50, '/sample_posters/small/s-2.jpg', '/sample_posters/banner/drama.webp', 4.0, 'Approved'),
(3, 0, 'Don Juan', 'Drama', 'Witness the captivating tale of Don Juan unfold...', '2024-06-20', '19:30', '22:30', 'Teatro Real, Madrid, Spain', 700, 180, '/sample_posters/small/s-3.jpg', '/sample_posters/banner/drama.webp', 4.8, 'Approved'),
(4, 0, 'Romeo and Juliet', 'Drama', 'Experience the timeless tragedy of Romeo and Juliet...', '2024-07-15', '20:00', '23:00', 'Globe Theatre, London, UK', 900, 120, '/sample_posters/small/s-4.jpg', '/sample_posters/banner/drama.webp', 4.9, 'Approved'),
(5, 0, 'Alton\'s Jazz', 'Concert', 'Immerse yourself in the soulful melodies of Alton\'s Jazz...', '2024-08-10', '21:00', '00:00', 'Blue Note Jazz Club, New York, NY', 500, 75, '/sample_posters/small/s-5.jpg', '/sample_posters/banner/orchestra.jpeg', 4.7, 'Approved'),
(6, 0, 'ADELE LIVE CONCERT', 'Concert', 'Get ready for an electrifying performance by Adele...', '2024-09-05', '20:30', '23:30', 'Staples Center, Los Angeles, CA', 1500, 200, '/sample_posters/small/s-6.jpg', '/sample_posters/banner/concert.webp', 5.0, 'Approved'),
(7, 0, 'RACHELE GENSOLIN PIANO RECITAL', 'Concert', 'Experience the masterful piano performance by Rachele Gensolin...', '2024-10-20', '19:00', '22:00', 'Carnegie Hall, New York, NY', 600, 90, '/sample_posters/small/s-7.jpg', '/sample_posters/banner/orchestra.jpeg', 4.6, 'Approved'),
(8, 0, 'Senio\'s Recital Marianne Rohbock with Nie Maughan', 'Concert', 'Join us for an evening of classical music with Senio\'s Recital...', '2024-11-15', '18:00', '21:00', 'The Kennedy Center, Washington D.C., USA', 550, 110, '/sample_posters/small/s-8.jpg', '/sample_posters/banner/orchestra.jpeg', 4.5, 'Approved'),
(9, 0, 'TORONTO RAPTORS', 'Sport', 'Cheer for the Toronto Raptors as they take on their rivals...', '2024-12-10', '19:30', '22:30', 'Scotiabank Arena, Toronto, Canada', 20000, 60, '/sample_posters/small/s-9.jpg', '/sample_posters/banner/sport.jpeg', 4.3, 'Approved'),
(10, 0, 'LFC vs MANCHESTER UNITED', 'Sport', 'Witness the fierce rivalry between Liverpool FC and Manchester United...', '2025-01-05', '17:00', '20:00', 'Anfield, Liverpool, UK', 54000, 250, '/sample_posters/small/s-10.jpg', '/sample_posters/banner/sport.jpeg', 4.8, 'Approved'),
(11, 0, 'FIRST TEAM TO 60 WINS', 'Sport', 'Don\'t miss the excitement as teams battle it out to reach 60 points first...', '2025-02-20', '15:00', '18:00', 'Barclays Center, Brooklyn, NY', 18000, 100, '/sample_posters/small/s-11.jpg', '/sample_posters/banner/sport.jpeg', 4.4, 'Approved'),
(12, 0, 'MANCHESTER UNITED vs WOLVERHAMPTON', 'Sport', 'Catch the action-packed match between Manchester United and Wolverhampton...', '2025-03-15', '16:30', '19:30', 'Old Trafford, Manchester, UK', 76000, 95, '/sample_posters/small/s-12.jpg', '/sample_posters/banner/sport.jpeg', null, 'Pending');


