name: Full Stack Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        # distribution of OpenJDK
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    # Run Java tests
    - name: Test with Maven
      run: mvn test

    # Set up Node.js for React environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.2' # Specify the version used in your project

    # Install React dependencies and run tests
    - name: Install dependencies and run React tests
      run: |
        cd path/to/your/react/app # Update this to the path of the react app
        npm install
        npm test
